# Site settings
title: Madison Kuduk 
description: Madison Kuduk personal website
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Madison Kuduk
user_description: Computer Science and Mathematics major with a minor in Bioinformatics. Interested in Data analysis, primarily genomic data.
user_title: Student
email: mkuduk@arcadia.edu
github_username:  https://github.com/mkuduk


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
